{
 "title": "Infiniband",
 "description": "Use Prometheus and infiniband-exporter to collect the stats on a entire Infiniband fabric from a single management node.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Informative",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RX (node_exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(node_infiniband_port_data_received_bytes_total[5m]))",
     "legendFormat": "Received {{instance}}"
    }
   ]
  },
  {
   "title": "TX (node_exporter)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(topk(10,rate(node_infiniband_port_data_transmitted_bytes_total[5m])))",
     "legendFormat": "Transmitted {{instance}}"
    }
   ]
  },
  {
   "title": "portxmitdata",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(infiniband_portxmitdata_total[2m])*4*8) != 0",
     "legendFormat": "{{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  },
  {
   "title": "portrcvdata",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(infiniband_portrcvdata_total[2m])*4*8) != 0",
     "legendFormat": "{{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors (should be empty)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(infiniband_symbolerrorcounter_total[2m])) != 0",
     "legendFormat": "Symbol {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_linkerrorrecoverycounter_total[2m])) != 0",
     "legendFormat": "Link error recovery {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_locallinkintegrityerrors_total[2m])) != 0",
     "legendFormat": "Local link integrity {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portbufferoverrunerrors_total[2m])) != 0",
     "legendFormat": "Port buffer overrun {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portlocalphysicalerrors_total[2m])) != 0",
     "legendFormat": "Port local physical {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portrcvremotephysicalerrors_total[2m])) != 0",
     "legendFormat": "Port rcv remote physical {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portdlidmappingerrors_total[2m])) != 0",
     "legendFormat": "Port DLID mapping {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  },
  {
   "title": "portxmitwait",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(infiniband_portxmitwait_total[2m])) != 0",
     "legendFormat": "{{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  },
  {
   "title": "portxmitdiscard",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10,rate(infiniband_portxmitdiscards_total[2m])) != 0",
     "legendFormat": "{{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  }
 ]
}