{
 "title": "InfiniBand Exporter Detailed",
 "description": "Use Prometheus and infiniband-exporter to collect the stats on a entire Infiniband fabric from a single management node.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "label": "Node", "query": { "query": "label_values(local_name)" } }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors from STDERR by IBQueryErrors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "infiniband_query_failed_error{local_name=~\"$Node\"}",
     "legendFormat": "QUERY FAILED {{counter_name}} {{local_name}}-{{port}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(infiniband_linkdownedcounter_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "LINK DOWNED {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_symbolerrorcounter_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "SYMBOL {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_linkerrorrecoverycounter_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "LINK ERROR RECOVERY {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_portxmitdiscards_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "PORT PACKETS DISCARDS {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_portbufferoverrunerrors_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "PORT BUFFER OVERRUN {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_portlocalphysicalerrors_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "PORT LOCAL PHYSICAL {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_portrcvremotephysicalerrors_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "PORT RCV REMOTE PHYSICAL {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_portinactivediscards_total{local_name=~\"$Node\"}[30m]) * 1800  > 0",
     "legendFormat": "PORT INACTIVE DISCARD {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_portdlidmappingerrors_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "PORT DLID MAPPING {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_locallinkintegrityerrors_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "LOCAL LINK INTEGRITY {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_vl15dropped_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "VL15 DROPPED {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_portneighbormtudiscards_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "PORT NEIGHBOR MTU DISCARDS {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "rate(infiniband_portrcverrors_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "PORT RCV ERRORS {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  },
  {
   "title": "Informative",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "infiniband_speed{local_name=~\"$Node\"} * infiniband_width{local_name=~\"$Node\"}",
     "legendFormat": "{{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  },
  {
   "title": "Port Transmit Wait",
   "type": "graph",
   "description": "The number of ticks during which the port had data to transmit but no data was sent during the entire tick (either because of insufficient credits or because of lack of arbitration).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "rate(infiniband_portxmitwait_total{local_name=~\"$Node\"}[30m]) * 1800 > 0",
     "legendFormat": "{{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  }
 ]
}