{
 "title": "InfiniBand Exporter Overview",
 "description": "Use Prometheus and infiniband-exporter to collect the stats on a entire Infiniband fabric from a single management node.",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status (1=OK,0=FAILURE/INCOMPLETE)",
   "type": "graph",
   "description": "If 1 the exporter was successful scraped, otherwise 0 on failure or incomplete",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "infiniband_scrape_ok", "legendFormat": "Status" }
   ]
  },
  {
   "title": "Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "infiniband_scrape_duration_seconds",
     "legendFormat": "Scrape duration seconds"
    },
    {
     "expr": "infiniband_ibqueryerrors_duration_seconds",
     "legendFormat": "IBQueryErrors duration seconds"
    }
   ]
  },
  {
   "title": "Errors from STDERR by IBQueryErrors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(infiniband_bad_status_error)",
     "legendFormat": "infiniband_bad_status_error"
    },
    {
     "expr": "count(infiniband_query_failed_error)",
     "legendFormat": "infiniband_query_failed_error"
    },
    {
     "expr": "count(infiniband_mad_rpc_failed_error)",
     "legendFormat": "infiniband_mad_rpc_failed_error"
    },
    {
     "expr": "count(infiniband_query_cap_mask_error)",
     "legendFormat": "infiniband_query_cap_mask_error"
    },
    { "expr": "count(infiniband_print_error)", "legendFormat": "infiniband_print_error" }
   ]
  },
  {
   "title": "Counter Overview",
   "type": "table",
   "description": "Probably most important counter metrics",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(infiniband_linkdownedcounter_total{component=\"ca\"}[30m]) * 1800 > 0",
     "legendFormat": "linkdownedcounter"
    },
    {
     "expr": "rate(infiniband_symbolerrorcounter_total{component=\"ca\"}[30m]) * 1800 > 0",
     "legendFormat": "symbolerrorcounter"
    },
    {
     "expr": "rate(infiniband_infiniband_portxmitwait_total{component=\"ca\"}[30m]) * 1800 > 0",
     "legendFormat": "portxmitwait"
    },
    {
     "expr": "rate(infiniband_portxmitdiscards_total{component=\"ca\"}[30m]) * 1800 > 0",
     "legendFormat": "portxmitdiscards"
    },
    {
     "expr": "rate(infiniband_portrcvremotephysicalerrors_total{component=\"ca\"}[30m]) * 1800 > 0",
     "legendFormat": "portrcvremotephysicalerrors"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors on CA per Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(infiniband_linkdownedcounter_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "LINK DOWNED"
    },
    {
     "expr": "sum(rate(infiniband_symbolerrorcounter_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "SYMBOL"
    },
    {
     "expr": "sum(rate(infiniband_linkerrorrecoverycounter_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "LINK ERROR RECOVERY"
    },
    {
     "expr": "sum(rate(infiniband_portxmitdiscards_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT PACKETS DISCARDS"
    },
    {
     "expr": "sum(rate(infiniband_portbufferoverrunerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT BUFFER OVERRUN"
    },
    {
     "expr": "sum(rate(infiniband_portlocalphysicalerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT LOCAL PHYSICAL"
    },
    {
     "expr": "sum(rate(infiniband_portrcvremotephysicalerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT RCV REMOTE PHYSICAL"
    },
    {
     "expr": "sum(rate(infiniband_portinactivediscards_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT INACTIVE DISCARD"
    },
    {
     "expr": "sum(rate(infiniband_portdlidmappingerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT DLID MAPPING"
    },
    {
     "expr": "sum(rate(infiniband_locallinkintegrityerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "LOCAL LINK INTEGRITY"
    },
    {
     "expr": "sum(rate(infiniband_vl15dropped_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "VL15 DROPPED"
    },
    {
     "expr": "sum(rate(infiniband_portneighbormtudiscards_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT NEIGHBOR MTU DISCARDS"
    },
    {
     "expr": "sum(rate(infiniband_portrcverrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT RCV ERRORS"
    }
   ]
  },
  {
   "title": "Top Errors on CA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(infiniband_linkdownedcounter_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "LINK DOWNED {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10, rate(infiniband_symbolerrorcounter_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "SYMBOL {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10, rate(infiniband_linkerrorrecoverycounter_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "LINK ERROR RECOVERY {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10, rate(infiniband_portxmitdiscards_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT PACKETS DISCARDS {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portbufferoverrunerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT BUFFER OVERRUN {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portlocalphysicalerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT LOCAL PHYSICAL {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portrcvremotephysicalerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT RCV REMOTE PHYSICAL {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portinactivediscards_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT INACTIVE DISCARD {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portdlidmappingerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT DLID MAPPING {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_locallinkintegrityerrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "LOCAL LINK INTEGRITY {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_vl15dropped_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "VL15 DROPPED {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portneighbormtudiscards_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT NEIGHBOR MTU DISCARDS {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portrcverrors_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT RCV ERRORS {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  },
  {
   "title": "Errors on Switches per Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(infiniband_linkdownedcounter_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "LINK DOWNED"
    },
    {
     "expr": "sum(rate(infiniband_symbolerrorcounter_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "SYMBOL"
    },
    {
     "expr": "sum(rate(infiniband_linkerrorrecoverycounter_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "LINK ERROR RECOVERY"
    },
    {
     "expr": "sum(rate(infiniband_portxmitdiscards_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT PACKETS DISCARDS"
    },
    {
     "expr": "sum(rate(infiniband_portbufferoverrunerrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT BUFFER OVERRUN"
    },
    {
     "expr": "sum(rate(infiniband_portlocalphysicalerrors_total{component=\"switch\"}[30m]) * 1800 ) > 0",
     "legendFormat": "PORT LOCAL PHYSICAL"
    },
    {
     "expr": "sum(rate(infiniband_portrcvremotephysicalerrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT RCV REMOTE PHYSICAL"
    },
    {
     "expr": "sum(rate(infiniband_portinactivediscards_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT INACTIVE DISCARD"
    },
    {
     "expr": "sum(rate(infiniband_portdlidmappingerrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT DLID MAPPING"
    },
    {
     "expr": "sum(rate(infiniband_locallinkintegrityerrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "LOCAL LINK INTEGRITY"
    },
    {
     "expr": "sum(rate(infiniband_vl15dropped_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "VL15 DROPPED"
    },
    {
     "expr": "sum(rate(infiniband_portneighbormtudiscards_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT NEIGHBOR MTU DISCARDS"
    },
    {
     "expr": "sum(rate(infiniband_portrcverrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT RCV ERRORS"
    }
   ]
  },
  {
   "title": "Top Errors on Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(infiniband_linkdownedcounter_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "LINK DOWNED {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10, rate(infiniband_symbolerrorcounter_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "SYMBOL {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10, rate(infiniband_linkerrorrecoverycounter_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "LINK ERROR RECOVERY {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10, rate(infiniband_portxmitdiscards_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT PACKETS DISCARDS {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portbufferoverrunerrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT BUFFER OVERRUN {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portlocalphysicalerrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT LOCAL PHYSICAL {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portrcvremotephysicalerrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT RCV REMOTE PHYSICAL {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portinactivediscards_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT INACTIVE DISCARD {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portdlidmappingerrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT DLID MAPPING {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_locallinkintegrityerrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "LOCAL LINK INTEGRITY {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_vl15dropped_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "VL15 DROPPED {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portneighbormtudiscards_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT NEIGHBOR MTU DISCARDS {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    },
    {
     "expr": "topk(10,rate(infiniband_portrcverrors_total{component=\"switch\"}[30m]) * 1800) > 0",
     "legendFormat": "PORT RCV ERRORS {{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  },
  {
   "title": "Informative",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number Active Ports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(infiniband_speed{component=\"switch\"})",
     "legendFormat": "Switch"
    },
    {
     "expr": "count(infiniband_speed{component=\"ca\"})",
     "legendFormat": "Channel Adapter"
    }
   ]
  },
  {
   "title": "Top Port Transmit Wait",
   "type": "graph",
   "description": "The number of ticks during which the port had data to transmit but no data was sent during the entire tick (either because of insufficient credits or because of lack of arbitration).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short", "label": "Ticks" }
   ],
   "targets": [
    {
     "expr": "topk(2, rate(infiniband_portxmitwait_total{component=\"ca\"}[30m]) * 1800) > 0",
     "legendFormat": "{{local_name}}-{{local_port}} to {{remote_name}}-{{remote_port}}"
    }
   ]
  }
 ]
}