{
 "title": "Parallel File System exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "topk", "label": "Top Clients", "query": "1,3,5,10,15,20" },
   {
    "name": "fs",
    "query": "bbfs,fsa,fs00,fs04,fs08,fs09,fs10,fs12,fs13,fs14"
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(gpfs_perf_info{fs=~\"$fs\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PFS IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PFS Read IO",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_read_bytes_total{fs=~\"$fs\",instance=~\"$host\"}[$__rate_interval])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "PFS Read IO - Top Clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($topk, irate(gpfs_perf_read_bytes_total{fs=~\"$fs\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{fs}}"
    }
   ]
  },
  {
   "title": "PFS Write IO",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_write_bytes_total{fs=~\"$fs\",instance=~\"$host\"}[$__rate_interval])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "PFS Write IO - Top Clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($topk, irate(gpfs_perf_write_bytes_total{fs=~\"$fs\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{fs}}"
    }
   ]
  },
  {
   "title": "PFS Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PFS Read Operations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_operations_total{fs=~\"$fs\",instance=~\"$host\",operation=\"reads\"}[$__rate_interval])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "PFS Read Operations - Top Clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, irate(gpfs_perf_operations_total{fs=~\"$fs\",operation=\"reads\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{fs}}"
    }
   ]
  },
  {
   "title": "PFS Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_operations_total{fs=~\"$fs\",instance=~\"$host\",operation=\"writes\"}[$__rate_interval])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "PFS Write Operations - Top Clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, irate(gpfs_perf_operations_total{fs=~\"$fs\",operation=\"writes\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{fs}}"
    }
   ]
  },
  {
   "title": "PFS Metadata Operations",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(gpfs_perf_operations_total{fs=~\"$fs\",instance=~\"$host\",operation=~\"(closes|inode_updates|opens|read_dir)\"}[$__rate_interval])) by (fs)",
     "legendFormat": "{{fs}}"
    }
   ]
  },
  {
   "title": "PFS Metadata Operations - Top Clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($topk, sum(irate(gpfs_perf_operations_total{fs=~\"$fs\",operation=~\"(closes|inode_updates|opens|read_dir)\"}[$__rate_interval])) by (instance,fs))",
     "legendFormat": "{{instance}} - {{fs}}"
    }
   ]
  },
  {
   "title": "PFS Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Block Used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "1.0 - (sum(gpfs_fs_free_bytes{fs=~\"$fs\"}) / sum(gpfs_fs_size_bytes{fs=~\"$fs\"}))"
      }
     ]
    },
    {
     "title": "Inodes Used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(gpfs_fs_used_inodes{fs=~\"$fs\"}) / sum(gpfs_fs_inodes{fs=~\"$fs\"})"
      }
     ]
    },
    {
     "title": "Inodes Allocated",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(gpfs_fs_allocated_inodes{fs=~\"$fs\"}) / sum(gpfs_fs_inodes{fs=~\"$fs\"})"
      }
     ]
    },
    {
     "title": "Metadata Used",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "1.0 - (sum(gpfs_fs_metadata_free_bytes{fs=~\"$fs\"}) / sum(gpfs_fs_metadata_size_bytes{fs=~\"$fs\"}))"
      }
     ]
    }
   ]
  }
 ]
}